var express = require('express');
var mongodb = require('mongodb');
const MimeNode = require('nodemailer/lib/mime-node');
const { connectDb, db } = require('../../config');
var router = express.Router();

// Creating a Shortend Url and Store in Db
router.post('/create/:id', async function(req, res, next) {
    
    try {
        const db = await connectDb();
        const shorten = generateUrl(7).trim();
        await db.collection("shortenUrl").insertOne({userId : mongodb.ObjectId(req.params.id), shortenUrl : shorten, longUrl : req.body.longUrl, views : 0});

        res.json(shorten);
    } catch (error) {
        console.log(error);
        res.status(500).json({message : "Something Went Wrong in Shorten Url"})
    }
});

//Redirecting to long URL
router.get("/:urlId", async function(req,res,next){

    try {
        const db = await connectDb();
        let shortenUrl = await db.collection("shortenUrl").findOne({shortenUrl : req.params.urlId});
        if(shortenUrl){
            await db.collection("shortenUrl").updateOne({shortenUrl : req.params.urlId},{$inc : { views : 1}});
            res.redirect(shortenUrl.longUrl);
        }else{
            res.status(404).status({message : "Url Not Found"});
        }
    } catch (error) {
        console.log(error);
        res.status(500).json({message : "Something Went Wrong in Redirecting Url"})
    }
})

//All the URL generated by User
router.get("/your-url/:userId", async function(req,res,next){

    try {
        const db = await connectDb();
        const URL = await db.collection("shortenUrl").aggregate([{$match : { userId : mongodb.ObjectId(req.params.userId)}}]).toArray();

        if(URL){
            res.json(URL)
        }else{
            res.json({message : "No Url generated"});
        }

    } catch (error) {
        console.log(error);
        res.status(500).json({message : "No Url Generated"})
    }
})

// Delete Generated Url
router.delete("/delete/:urlId", async function (req,res,next){

    try {
        const db = await connectDb();
        await db.collection("shortenUrl").deleteOne({_id : mongodb.ObjectId(req.params.urlId)});

        res.json({message : "Url deleted"});
    } catch (error) {
        console.log(error);
        res.status(500).json({message : "Something Went Wrong in Deleting Url"})
    }
})

//Function to Generate Random Shorten URL
function generateUrl(length){
    let result = ' ';
    const characters ='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const charactersLength = characters.length;
    for ( let i = 0; i < length; i++ ) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }

    return result;
}

module.exports = router;
